### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by eaedk** [jc639/pytorch-handwritingCTC#2]
Hi, please can you say me how many epochs have you trained the model and how longer ? (for line)

**Comment by jc639** [comment]
About a couple of hours, had access to Nivdia tesla 32GB GPU at the time, so could have quite a large batch size. Also using transfer learning with the pretrained resnet weights helps.

**Comment by eaedk** [comment]
ok thanks, thank you a lot for your model, it really helpful to learn more about deep learning. I worked on a handwriting predictor based on a transformer model but I had some issue with the model's performance and after I found your repository and I learn many different things

**Comment by eaedk** [comment]
Hi, please can you know other approaches or models to achieve better results on handwriting classification ?

**Comment by jc639** [comment]
Sorry I don't know much more than what I implemented here - mostly from reading Harald Scheidl's blogposts and repos as linked in the README. I don't really work on deep learning all that much, unfortunately. I would have thought replacing the LSTM with a transformer would be the way to go.

You may be interested in the fullstackdeeplearning course this year, they are doing this exact problem in the labs - of handwriting recognition and start with the CNN-LSTM then replace with transformer. https://fullstackdeeplearning.com/spring2021/
