### ISSUE TITLE
Characters in the IAM Dataset equals 78 not 79(?)

### ISSUE THREAD

**Issue by sambbhavgarg** [jc639/pytorch-handwritingCTC#3]
Hey
This is weird but I tried to compile your model with the pretrained weights and got the following error -

> RuntimeError: Error(s) in loading state_dict for CTCModel:
	size mismatch for rnn.atrous_conv.weight: copying a param with shape torch.Size([80, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([79, 1024, 1, 1]).
	size mismatch for rnn.atrous_conv.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([79]).

It's weird because it says in your README -

> and it can output 79 characters (A-Z,a-z,0-9, plus punctuation including space).

So I double checked the words.csv that I created using the words.txt file from the IAM Dataset using the following code -
```
from collections import Counter
len(Counter(pd.read_csv("./data/words.csv").iloc[:, -1].str.cat()).keys())
```
and the output is 78, not 79. Am I possibly doing something wrong? Due to this issue, the pretrained model fails to compile. Thanks in advance.

Sambbhav

**Comment by jc639** [comment]
I haven't been very clear there I don't think, the output size is :
`output_size=len(dataset.char_dict) + 1`

The plus 1 is for the special BLANK character in the CTC loss, so you are correct there are 78 keys in the Counter but there is one more in the output size. 

I think you have loaded the lines weights file for the word model? It would make sense why it is out by 1 - the lines have spaces, words don't.

**Comment by sambbhavgarg** [comment]
Im pretty sure ive loaded the lines weights file for the line model only, but I’ll still check it again tomorrow. The lines having spaces already could be a possible problem, hmm. Ill have to check.


Meanwhile, do you mind if i request certain changes to the README that would make it a little clearer?

**Comment by sambbhavgarg** [comment]
Could you perhaps reiterate on the format for the word_lines.csv file?

**Comment by jc639** [comment]
OK, i think there is a mismatch between the data you are loading and the weights you are loading then perhaps. 

These lines you wrote suggest you are loading the words.csv created from the IAM words, correct?
```
from collections import Counter
len(Counter(pd.read_csv("./data/words.csv").iloc[:, -1].str.cat()).keys())
```

But you have said you are loading the lines weights for the line model. Model output dimensions is defined by the Dataset class if you have followed the section in loading the line level model bit in the README using:
`output_size=len(dataset.char_dict) + 1`

The lines CSV should have pretty much the same format but point to and label the IAM Lines data:

file | ok | word
-- | -- | --
a01-000u-00-00.png | ok | This is a sentence 
a01-000u-00-01.png | ok | Here's another one
... | ... | ...


I can add this to the README if this is the confusion.

**Comment by sambbhavgarg** [comment]
Yeah thats about right, the word lines file corresponds to the lines model, and the words file corresponds to the words model, I forgot to update the latter while testing both. But yeah, I was just confused about the csv file for the lines dataset. It would be great if you could just add the structure that you’ve replied with here to the CSV. 


Thanks!
